import React from "react";
import { motion } from "framer-motion";
import {
  Sparkles,
  Target,
  Clock,
  TrendingDown,
  Eye,
  Thermometer,
  ShieldCheck,
  CheckCircle2,
} from "lucide-react";

const AccessSheathClinical = () => {
  const clinicalMetrics = [
    {
      title: "Improved Single-Session SFR",
      category: "STONE-FREE OUTCOME",
      description:
        "Active continuous fragment suction through the oblique side port drastically boosts single-procedure stone-free rate (SFR), eliminating residual dust and retropulsion.",
      icon: <Target className="h-6 w-6 text-primary" />,
      metric: "↑ 94%+",
      metricLabel: "Single-Session SFR",
    },
    {
      title: "Shortened Operative Time",
      category: "EFFICIENCY GAIN",
      description:
        "Instant evacuation of dust and fragments replaces laborious manual nitinol basket extraction, cutting operative time significantly and reducing patient anesthesia exposure.",
      icon: <Clock className="h-6 w-6 text-primary" />,
      metric: "↓ 40%",
      metricLabel: "Shorter OR Time",
    },
    {
      title: "Lowers Intrarenal Pressure (IRP)",
      category: "SEPSIS PREVENTION",
      description:
        "Maintains physiological intrarenal pressures well below 30 mmHg even during high-flow laser lithotripsy, effectively preventing pyelovenous backflow and urosepsis.",
      icon: <TrendingDown className="h-6 w-6 text-primary" />,
      metric: "< 25 mmHg",
      metricLabel: "Controlled IRP",
    },
    {
      title: "Reduced Thermal Load & Temperature",
      category: "RENAL PARENCHYMAL SAFETY",
      description:
        "Continuous saline inflow paired with negative-pressure egress flushes away thermal energy generated by high-power Holmium and Thulium lasers, protecting urothelium.",
      icon: <Thermometer className="h-6 w-6 text-primary" />,
      metric: "< 38°C",
      metricLabel: "Pyelocaliceal Temp",
    },
    {
      title: "Crystal-Clear Endoscopic Field",
      category: "VISUAL PRECISION",
      description:
        "Rapid aspiration of floating stone clouds, blood clots, and turbid fluid restores immaculate endoscopic visualization for safe laser aiming and mucosal inspection.",
      icon: <Eye className="h-6 w-6 text-primary" />,
      metric: "100%",
      metricLabel: "Visual Clarity",
    },
    {
      title: "Repeat Instrument Entry Pathway",
      category: "ANATOMICAL STABILITY",
      description:
        "Establishes a low-friction conduit through tortuous ureters and pelvic angles, protecting the ureteral mucosa from repeated instrument abrasion and shear injury.",
      icon: <ShieldCheck className="h-6 w-6 text-primary" />,
      metric: "0 Trauma",
      metricLabel: "Mucosal Conduit",
    },
  ];

  return (
    <section className="relative overflow-hidden bg-gradient-to-b from-slate-50 via-white to-slate-50 py-16 sm:py-24 border-t border-slate-100">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center">
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-4 py-1.5 text-xs font-bold tracking-widest text-primary uppercase"
          >
            <Sparkles className="h-3.5 w-3.5" />
            <span>EVIDENCE-BASED CLINICAL VALUE</span>
          </motion.div>

          <motion.h2
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.1 }}
            className="mt-4 text-2xl font-extrabold tracking-tight text-slate-900 sm:text-3xl lg:text-4xl"
          >
            Clinical Advantages in{" "}
            <span className="bg-gradient-to-r from-primary to-primary-dark bg-clip-text text-transparent">
              Flexible Ureteroscopy (RIRS)
            </span>
          </motion.h2>

          <motion.p
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.2 }}
            className="mx-auto mt-3 max-w-2xl text-xs leading-relaxed text-slate-600 sm:text-sm sm:leading-6"
          >
            Clinically, it broadens indications, improves single-session stone-free rate (SFR), shortens operative time, lowers intrarenal pressure and temperature, and enhances visualization and irrigation efficiency.
          </motion.p>
        </div>

        {/* 6 Metrics Grid */}
        <div className="mt-12 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {clinicalMetrics.map((item, idx) => (
            <motion.div
              key={item.title}
              initial={{ opacity: 0, y: 25 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.45, delay: idx * 0.08 }}
              className="group flex flex-col justify-between rounded-2xl border border-slate-200/90 bg-white p-6 shadow-xs transition-all duration-300 hover:-translate-y-1 hover:border-primary/50 hover:shadow-lg"
            >
              <div>
                <div className="flex items-center justify-between">
                  <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10 text-primary transition-colors group-hover:bg-primary group-hover:text-white">
                    {item.icon}
                  </div>
                  <div className="text-right">
                    <span className="text-xl sm:text-2xl font-black text-primary">
                      {item.metric}
                    </span>
                    <div className="text-[10px] font-semibold text-slate-400 uppercase">
                      {item.metricLabel}
                    </div>
                  </div>
                </div>

                <div className="mt-4 text-[10px] font-bold uppercase tracking-wider text-primary">
                  {item.category}
                </div>

                <h3 className="mt-1 text-base font-bold text-slate-900 group-hover:text-primary transition-colors">
                  {item.title}
                </h3>

                <p className="mt-2 text-xs sm:text-sm leading-relaxed text-slate-600">
                  {item.description}
                </p>
              </div>

              <div className="mt-5 border-t border-slate-100 pt-3 flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4 text-emerald-500 shrink-0" />
                <span className="text-xs font-semibold text-slate-700">
                  Validated in high-volume RIRS clinical centers
                </span>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default AccessSheathClinical;
